[workspace.package]
authors = ["l1x-team <info@l1x.foundation>"]
edition = "2021"
repository = "https://github.com/L1X-Foundation-VM/l1x-contracts/"

[workspace]
members = [
	"l1x-contracts/source_registry",
	"l1x-contracts/xtalk_swap_flow",
]
